version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tourist_db
    networks:
      - app-network

  fastapi:
    image: fastapi-image
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tourist_db
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge

